### ISSUE TITLE
Clicking girls button

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Web#2]
Clicking the girls' button should show the following page

Girls details which show the summarised view of Number of Girls Mapped, how many have missed and 3 age groups, 
1.10-15 yrs
2.16-19yrs
3. 20-24 yrs

- For missed Girls, we would expect a view for the list of girls who missed with the following information
1.Name of the girl
2. Village
3. VHT in charge of the village

- Lastly an aggregation for the details of mapped girls on the page
1.Total girls missed appointment in percentage
2. percentage of girls who have missed
3. percentage of girls who deliver from hospital

![page page 2](https://cloud.githubusercontent.com/assets/16231167/24658162/919a3d0c-1951-11e7-9cae-72ceb551e87e.png)

**Comment by Mukama1** [comment]
Please check the second range of ages. It should start from 16-19

**Comment by donrukanga1** [comment]
Thats correct , Thanks for the highlight
